export enum ReduxActionTypes {
  ADD_TODO_STARTED = 'ADD_TODO_STARTED',
  ADD_TODO_SUCEESS = 'ADD_TODO_SUCEESS',
  ADD_TODO_FAILED = 'ADD_TODO_FAILED',
  UPDATE_TODO_STARTED = 'UPDATE_TODO_STARTED',
  UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED',
  REMOVE_TODO_STARTED = 'REMOVE_TODO_STARTED',
  REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS',
  REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED',
  FETCH_TODOS_STARTED = 'FETCH_TODOS_STARTED',
  FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED',
}
